---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_sudoers: true
configure_terminal: false
configure_osx: true

dotfiles_repo: https://github.com/weyhmueller/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files: []

homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ansible-lint
  - asdf
  - autoconf
  - aws-shell
  - awscli
  - azure-cli
  - bfg
  - certigo
  - cfssl
  - coreutils
  - direnv
  - doctl
  - exif
  - emacs-plus
  - ffmpeg
  - fzf
  - ghq
  - git
  - git-cal
  - git-extras
  - git-flow-avh
  - git-lfs
  - git-plus
  - git-secrets
  - git-standup
  - gitmoji
  - github/gh/gh
  - go
  - gnutls
  - gpg
  - has
  - helm
  - httpie
  - hub
  - htop
  - iperf
  - jq
  - kubernetes-cli
  - lame
  - libevent
  - maven
  - mcrypt
  - ncurses
  - nmap
  - nnn
  - node
  - nvm
  - openssl
  - pv
  - php
  - readline
  - sipcalc
  - sqlite
  - ssh-copy-id
  - step
  - terraform
  - thefuck
  - timewarrior
  - tmux
  - todoist
  - vault
  - vim
  - wget
  - wrk
  - xz
  - yamllint
  - yarn
  - ykman
  - yq
  - yubico-piv-tool
  - zlib

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - adoptopenjdk/openjdk
  - graalvm/tap
  - kdabir/tap
  - sachaos/todoist
  - d12frosted/emacs-plus

homebrew_cask_accept_external_apps: true
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password-cli
  - alfred
  - adoptopenjdk8
  - bartender
  - calibre
  - chromedriver
  - cloudapp
  - dash
  - discord
  - docker
  - firefox
  - github
  - google-chrome
  - gpg-suite-no-mail
  - graalvm-ce-java8
  - grandperspective
  - handbrake
  - istat-menus
  - iterm2
  - java
  - jetbrains-toolbox
  - microsoft-office
  - microsoft-teams
  - nordvpn
  - pdf-expert
  - pliim
  - postman
  - skype
  - spotify
  - spotify-notifications
  - slack
  - teamviewer
  - tower
  - transmit
  - tweetbot
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - vuescan
  - webex-meetings
  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - {id: 904280696, name: "Things (3.12.2)"}
  - {id: 1362171212, name: "Caffeinated (1.17)"}
  - {id: 1461456897, name: "Tyme (2020.6)"}
  - {id: 409183694, name: "Keynote (10.0)"}
  - {id: 441258766, name: "Magnet (2.4.5)"}
  - {id: 585829637, name: "Todoist (7.2.6)"}
  - {id: 1333542190, name: "1Password 7 (7.4.4)"}
  - {id: 1142578753, name: " OmniGraffle (7.15)"}
  - {id: 1289197285, name: "MindNode (7.0.4)"}
  - {id: 409203825, name: "Numbers (10.0)"}
  - {id: 497799835, name: "Xcode (11.4)"}
  - {id: 1173932628, name: "Drop (1.5.2)"}
  - {id: 409201541, name: "Pages (10.0)"}
  - {id: 129035839, name: " Cardhop (1.3.3)"}
  - {id: 1449412482, name: "Reeder (4.2.3)"}
  - {id: 975937182, name: "Fantastical (3.0.8)"}
  - {id: 1179623856, name: "Pastebot (2.3)"}
  - {id: 549083868, name: "Display Menu (2.2.3)"}
  - {id: 1225570693, name: "Ulysses (18.7)"}
  - {id: 924726344, name: "Lieferungen (3.2.2)"}

mas_email: ""
mas_password: ""
mas_upgrade_all_apps: true

osx_script: "~/bin/osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
